Traceback (most recent call last):
  File "app_main.py", line 75, in run_toplevel
  File "./runner.py", line 42, in <module>
    os.execvpe(cmd[lang], ('', argv[lang]), env)
  File "/home/magimagi/.local/pypy-2.3.1-linux64/lib-python/2.7/os.py", line 353, in execvpe
    _execvpe(file, args, env)
  File "/home/magimagi/.local/pypy-2.3.1-linux64/lib-python/2.7/os.py", line 368, in _execvpe
    func(file, *argrest)
OSError: [Errno 13] Permission denied
